version: "3.9"

services:
  mongo:
    image: mongo:5
    hostname: mongo
    # command: --replSet hb0 --bind_ip localhost,mongo
    command: --replSet hb0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  scheduler:
    build: .
    image: ${HONEYBEE_IMAGE}
    command: honeybee scheduler
    environment:
      REDIS_URI: redis://redis
      JOB_CONCURRENCY: ${JOB_CONCURRENCY}
      HOLODEX_MAX_UPCOMING_HOURS: ${HOLODEX_MAX_UPCOMING_HOURS}
      HOLODEX_API_KEY: ${HOLODEX_API_KEY}
      CACHE_PATH: /cache
    volumes:
      - ${DATA_DIR:-./data}/cache:/cache
      - "./dist:/app/dist"
    depends_on:
      - redis

  worker:
    image: ${HONEYBEE_IMAGE}
    environment:
      REDIS_URI: redis://redis
      MONGO_URI: mongodb://mongo/honeybee
      JOB_CONCURRENCY: ${JOB_CONCURRENCY}
      DEBUG: masterchat
    volumes:
      - "./dist:/app/dist"
    depends_on:
      - redis
      - mongo
