apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: honeybee
resources:
  - ../../base
images:
  - name: ghcr.io/stu43005/honeybee/honeybee
    newTag: dev
    # newTag: ${IMAGE_TAG:=sha-${GITHUB_SHA:0:7}}
replicas:
  - name: worker
    count: 2

# Flux GitOps
