apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: honeybee-deploy
  namespace: honeybee
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - create
  - apply
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - create
  - apply
  - update
  - patch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - apply
  - update
  - patch
