apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chats-archive-pvc
  labels:
    app.kubernetes.io/name: honeybee
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
