apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: discord-bot
    app.kubernetes.io/component: discord-bot
    app.kubernetes.io/name: honeybee
    app.kubernetes.io/version: dev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
        app.kubernetes.io/component: discord-bot
        app.kubernetes.io/name: honeybee
        app.kubernetes.io/version: dev
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: discord-bot
          image: ghcr.io/stu43005/honeybee/honeybee
          imagePullPolicy: Always
          args:
            - "discord-bot"
          env:
            - name: HOLODEX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: holodex-api-key
                  key: key
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: honeybee-mongodb
                  key: MONGO_URI
            - name: DISCORD_ID
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_ID
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_TOKEN
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api-key
                  key: key
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: honeybee-redis
                  key: REDIS_URI
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: discord-oauth-secrets
                  key: GOOGLE_OAUTH_CLIENT_ID
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: discord-oauth-secrets
                  key: GOOGLE_OAUTH_CLIENT_SECRET
            - name: DISCORD_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: discord-oauth-secrets
                  key: DISCORD_OAUTH_CLIENT_ID
            - name: DISCORD_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: discord-oauth-secrets
                  key: DISCORD_OAUTH_CLIENT_SECRET
            - name: OAUTH_PUBLIC_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: discord-oauth-secrets
                  key: OAUTH_PUBLIC_BASE_URL
          resources: {}
          ports:
            - name: http-port
              containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: http-port
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-port
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: honeybee-discord-bot
  labels:
    app: discord-bot
    app.kubernetes.io/component: discord-bot
    app.kubernetes.io/name: honeybee
    app.kubernetes.io/version: dev
spec:
  ports:
    - name: http-port
      port: 3000
      targetPort: 3000
  type: ClusterIP
  selector:
    app: discord-bot
