apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/name: honeybee
    app.kubernetes.io/version: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/name: honeybee
        app.kubernetes.io/version: dev
    spec:
      containers:
        - name: scheduler
          image: ghcr.io/stu43005/honeybee/honeybee
          imagePullPolicy: Always
          args:
            - "scheduler"
          envFrom:
            - configMapRef:
                name: honeybee-config
          env:
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: honeybee-secrets
                  key: REDIS_URI
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: honeybee-secrets
                  key: MONGO_URI
          resources: {}
