apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: honeybee
    app.kubernetes.io/version: dev
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/name: honeybee
        app.kubernetes.io/version: dev
    spec:
      containers:
        - name: webhook
          image: ghcr.io/stu43005/honeybee/honeybee
          imagePullPolicy: Always
          args:
            - "webhook"
          envFrom:
            - configMapRef:
                name: honeybee-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: honeybee-secrets
                  key: MONGO_URI
          resources: {}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: webhook
