apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/name: honeybee
    app.kubernetes.io/version: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        app.kubernetes.io/component: worker
        app.kubernetes.io/name: honeybee
        app.kubernetes.io/version: dev
    spec:
      containers:
        - name: worker
          image: ghcr.io/stu43005/honeybee/honeybee
          imagePullPolicy: Always
          args:
            - "worker"
          env:
            - name: HOLODEX_FETCH_ORG
              valueFrom:
                secretKeyRef:
                  name: honeybee-secrets
                  key: HOLODEX_FETCH_ORG
            - name: JOB_CONCURRENCY
              valueFrom:
                secretKeyRef:
                  name: honeybee-secrets
                  key: JOB_CONCURRENCY
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: honeybee-redis
                  key: REDIS_URI
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: honeybee-mongodb
                  key: MONGO_URI
          resources: {}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: worker
